
import matplotlib.pyplot as plt
from fpdf import FPDF
import os
from services.ml_engine import WastePredictor

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Government Waste Management Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def create_chart_image(df, predicted_val, next_month_label="Next Month"):
    """
    Generates a line chart: Historical (Solid) vs Prediction (Dotted Red).
    """
    month_map = {
        "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4, "May": 5, "Jun": 6,
        "Jul": 7, "Aug": 8, "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12
    }
    
    # Sort data
    df_chart = df.copy()
    df_chart['month_num'] = df_chart['month'].map(month_map)
    df_chart = df_chart.sort_values('month_num')
    
    months = df_chart['month'].tolist()
    usage = df_chart['used_kg'].tolist()
    
    # Append prediction
    months.append("Next Month")
    usage.append(predicted_val)
    
    plt.figure(figsize=(8, 4))
    
    # Plot historical
    plt.plot(months[:-1], usage[:-1], marker='o', label='Historical Usage', color='blue')
    
    # Plot prediction connection (Last historical -> Prediction)
    plt.plot(months[-2:], usage[-2:], linestyle='--', marker='x', color='red', label='Prediction')
    
    plt.title("Paper Waste Trend & Prediction")
    plt.xlabel("Month")
    plt.ylabel("Usage (kg)")
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.5)
    
    temp_filename = "temp_chart.png"
    plt.savefig(temp_filename)
    plt.close()
    
    return temp_filename

def generate_dept_pdf(dept_name, df, report_type='Monthly'):
    """
    Generates a PDF report for the department.
    """
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # 1. Title Section
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 10, f"Department: {dept_name}", 0, 1, 'L')
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 10, f"Report Type: {report_type} | Generated by AI System", 0, 1, 'L')
    pdf.ln(5)
    
    # 2. Statistics
    total_used = df['used_kg'].sum()
    total_recycled = df['recycled_kg'].sum()
    recycling_rate = (total_recycled / total_used * 100) if total_used else 0
    
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Summary Statistics", 0, 1)
    pdf.set_font("Arial", size=11)
    pdf.cell(0, 8, f"Total Paper Used: {total_used} kg", 0, 1)
    pdf.cell(0, 8, f"Total Recycled: {total_recycled} kg", 0, 1)
    pdf.cell(0, 8, f"Recycling Rate: {recycling_rate:.1f}%", 0, 1)
    pdf.ln(5)

    # 3. Prediction & Warning Logic
    predictor = WastePredictor()
    pred_val, warning, avg_usage = predictor.predict_next_month(df)
    
    # 4. Warning Box if needed
    if warning:
        pdf.set_fill_color(255, 200, 200) # Reddish background
        pdf.set_text_color(200, 0, 0) # Dark Red text
        pdf.set_font("Arial", 'B', 11)
        pdf.cell(0, 10, "[ALERT] WARNING: Projected waste exceeds sustainability limits!", 1, 1, 'C', fill=True)
        pdf.set_text_color(0, 0, 0) # Reset text
        pdf.ln(5)
    
    # 5. Chart
    chart_path = create_chart_image(df, pred_val)
    pdf.image(chart_path, x=10, w=190)
    os.remove(chart_path) # Clean up
    pdf.ln(5)
    
    # 6. AI Recommendations
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "AI Recommendations", 0, 1)
    pdf.set_font("Arial", size=11)
    
    recommendations = [
        "- Switch to double-sided printing default.",
        "- Digitalize internal memos to reduce paper consumption.",
    ]
    if warning:
        recommendations.insert(0, "- IMMEDIATE ACTION: Review bulk printing requests.")
        recommendations.append("- Audit required for high-volume predicted usage.")
        
    for rec in recommendations:
        pdf.cell(0, 8, rec, 0, 1)
        
    # Output
    # Ensure directory exists? Streamlit usually handles temp files or we return bytes.
    # For now, let's just save to a temp path and read bytes to return, 
    # because Streamlit download button expects data.
    
    return pdf.output(dest='S').encode('latin-1', 'replace') # Return bytes
